name       : hunspell-fr
version    : 6.3
release    : 6
source     :
    - https://www.dicollecte.org/download/fr/hunspell-french-dictionaries-v6.3.zip : cc6c2d15073659d221487b45245e9eee9a4ed66c30c6dcf784326bab063c5266
license    : MPL-2.0
component  : spelling
summary    : French (classic) hunspell dictionaries
description: |
    French (classic) hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -Dm00644 fr-classique.dic $installdir/usr/share/hunspell/fr_FR.dic
    install -m00644 fr-classique.aff $installdir/usr/share/hunspell/fr_FR.aff

    pushd $installdir/usr/share/hunspell/
        for lang in fr_BE fr_CA fr_CH fr_LU; do
            ln -s fr_FR.aff $lang.aff
            ln -s fr_FR.dic $lang.dic
        done
    popd
