name       : hunspell-fr
version    : '6.4'
release    : 7
source     :
    - http://www.dicollecte.org/download/fr/hunspell-french-dictionaries-v6.4.zip : 20cddfc0cbd108fd2e9c4d75118c2d30080934f1285d1446b3ef7d8b1b7796d0
license    : MPL-2.0
component  : spelling
summary    : French (classic) hunspell dictionaries
description: |
    French (classic) hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -Dm00644 fr-classique.dic $installdir/usr/share/hunspell/fr_FR.dic
    install -m00644 fr-classique.aff $installdir/usr/share/hunspell/fr_FR.aff

    pushd $installdir/usr/share/hunspell/
        for lang in fr_BE fr_CA fr_CH fr_LU; do
            ln -s fr_FR.aff $lang.aff
            ln -s fr_FR.dic $lang.dic
        done
    popd
