name       : hunspell-fr
version    : 6.0.2
release    : 3
source     :
    - http://www.dicollecte.org/download/fr/hunspell-french-dictionaries-v6.0.2.zip : 434956a8f572494718a7d7e79af1d778a6a0192936305daa74e2ada297327af8
license    : MPL-2.0
component  : spelling
summary    : French (modern) hunspell dictionaries
description: |
    French (modern) hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -d -D -m 00755 $installdir/usr/share/hunspell
    install -m 00644 fr-moderne.dic $installdir/usr/share/hunspell/fr_FR.dic
    install -m 00644 fr-moderne.aff $installdir/usr/share/hunspell/fr_FR.aff

    pushd $installdir/usr/share/hunspell/
    fr_FR_aliases="fr_BE fr_CA fr_CH fr_LU"
    for lang in ${fr_FR_aliases}; do
        ln -s fr_FR.aff $lang.aff
        ln -s fr_FR.dic $lang.dic
    done
    popd
