name       : hunspell-fr
version    : 6.4.1
release    : 8
source     :
    - https://grammalecte.net/download/fr/hunspell-french-dictionaries-v6.4.1.zip : 744e77a3bd115144fa3131485231638d41c21e65ed757bfc576ccec1dcc9c6cc
license    : MPL-2.0
component  : spelling
summary    : French (classic) hunspell dictionaries
description: |
    French (classic) hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -Dm00644 fr-classique.dic $installdir/usr/share/hunspell/fr_FR.dic
    install -m00644 fr-classique.aff $installdir/usr/share/hunspell/fr_FR.aff

    pushd $installdir/usr/share/hunspell/
        for lang in fr_BE fr_CA fr_CH fr_LU; do
            ln -s fr_FR.aff $lang.aff
            ln -s fr_FR.dic $lang.dic
        done
    popd
