name       : hunspell-fr
version    : '7.0'
release    : 9
source     :
    - https://grammalecte.net/download/fr/hunspell-french-dictionaries-v7.0.zip : eb7ac36dc14b9c3e3c0cabae0f90304a137da8e6ae607bcaf56d65720fbd097f
license    : MPL-2.0
component  : office.spelling
summary    : French (classic) hunspell dictionaries
description: |
    French (classic) hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -Dm00644 fr-classique.dic $installdir/usr/share/hunspell/fr_FR.dic
    install -m00644 fr-classique.aff $installdir/usr/share/hunspell/fr_FR.aff

    pushd $installdir/usr/share/hunspell/
        for lang in fr_BE fr_CA fr_CH fr_LU; do
            ln -s fr_FR.aff $lang.aff
            ln -s fr_FR.dic $lang.dic
        done
    popd
