name       : hunspell-fr
version    : 6.1
release    : 4
source     :
    - https://www.dicollecte.org/download/fr/hunspell-french-dictionaries-v6.1.zip : 0c6acc29d3ec88feed4e4772af4521af1d52ce3fb092e685d474486e06fc5070
license    : MPL-2.0
component  : spelling
summary    : French (classic) hunspell dictionaries
description: |
    French (classic) hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -d -D -m 00755 $installdir/usr/share/hunspell
    install -m 00644 fr-classique.dic $installdir/usr/share/hunspell/fr_FR.dic
    install -m 00644 fr-classique.aff $installdir/usr/share/hunspell/fr_FR.aff

    pushd $installdir/usr/share/hunspell/
    fr_FR_aliases="fr_BE fr_CA fr_CH fr_LU"
    for lang in ${fr_FR_aliases}; do
        ln -s fr_FR.aff $lang.aff
        ln -s fr_FR.dic $lang.dic
    done
    popd
