name       : hunspell-fr
version    : 6.2
release    : 5
source     :
    - https://www.dicollecte.org/download/fr/hunspell-french-dictionaries-v6.2.zip : c98147b99518a5aa51d51db58d6a153377bb9f366ebe8a21a2faa05b6c76308d
license    : MPL-2.0
component  : spelling
summary    : French (classic) hunspell dictionaries
description: |
    French (classic) hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -d -D -m 00755 $installdir/usr/share/hunspell
    install -m 00644 fr-classique.dic $installdir/usr/share/hunspell/fr_FR.dic
    install -m 00644 fr-classique.aff $installdir/usr/share/hunspell/fr_FR.aff

    pushd $installdir/usr/share/hunspell/
    fr_FR_aliases="fr_BE fr_CA fr_CH fr_LU"
    for lang in ${fr_FR_aliases}; do
        ln -s fr_FR.aff $lang.aff
        ln -s fr_FR.dic $lang.dic
    done
    popd
